// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDxwOyQDgEB1cUe5QU_b6l6SNUTkiAdf0',
    appId: '1:44385611967:web:40ed00b21219bd5bf8960a',
    messagingSenderId: '44385611967',
    projectId: 'selfcare-c5d55',
    authDomain: 'selfcare-c5d55.firebaseapp.com',
    storageBucket: 'selfcare-c5d55.firebasestorage.app',
    measurementId: 'G-R6TX4R6R9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpMey2fP6NQE3J4cbWw4CWt6YuGBNO10',
    appId: '1:44385611967:android:93b8dad421ad77f8f8960a',
    messagingSenderId: '44385611967',
    projectId: 'selfcare-c5d55',
    storageBucket: 'selfcare-c5d55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqNJ__P7Kkw1R1EuGTCHZ8z3YlYzjGyo',
    appId: '1:44385611967:ios:aa51fff84530bda9f8960a',
    messagingSenderId: '44385611967',
    projectId: 'selfcare-c5d55',
    storageBucket: 'selfcare-c5d55.firebasestorage.app',
    iosBundleId: 'com.example.selfcareProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqNJ__P7Kkw1R1EuGTCHZ8z3YlYzjGyo',
    appId: '1:44385611967:ios:aa51fff84530bda9f8960a',
    messagingSenderId: '44385611967',
    projectId: 'selfcare-c5d55',
    storageBucket: 'selfcare-c5d55.firebasestorage.app',
    iosBundleId: 'com.example.selfcareProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDxwOyQDgEB1cUe5QU_b6l6SNUTkiAdf0',
    appId: '1:44385611967:web:1925981970a2a2faf8960a',
    messagingSenderId: '44385611967',
    projectId: 'selfcare-c5d55',
    authDomain: 'selfcare-c5d55.firebaseapp.com',
    storageBucket: 'selfcare-c5d55.firebasestorage.app',
    measurementId: 'G-BK11VY4QZW',
  );
}
