// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlcpQZI3TgfuP-bf1sCuhQjSNFXAdUvs',
    appId: '1:609604667702:web:c38c55273e0638e4558b97',
    messagingSenderId: '609604667702',
    projectId: 'selfcare-1476e',
    authDomain: 'selfcare-1476e.firebaseapp.com',
    storageBucket: 'selfcare-1476e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ITfkOctFd-8tgO0O52q9kM55k7rLZgo',
    appId: '1:609604667702:android:a5c085ba60873b18558b97',
    messagingSenderId: '609604667702',
    projectId: 'selfcare-1476e',
    storageBucket: 'selfcare-1476e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPV86bYifMqGZKRUfMR3gsrHJ5ScxXxs',
    appId: '1:609604667702:ios:49e500c6cf998ee7558b97',
    messagingSenderId: '609604667702',
    projectId: 'selfcare-1476e',
    storageBucket: 'selfcare-1476e.firebasestorage.app',
    iosBundleId: 'com.example.selfcareProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPV86bYifMqGZKRUfMR3gsrHJ5ScxXxs',
    appId: '1:609604667702:ios:49e500c6cf998ee7558b97',
    messagingSenderId: '609604667702',
    projectId: 'selfcare-1476e',
    storageBucket: 'selfcare-1476e.firebasestorage.app',
    iosBundleId: 'com.example.selfcareProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNlcpQZI3TgfuP-bf1sCuhQjSNFXAdUvs',
    appId: '1:609604667702:web:37726298edfa70ed558b97',
    messagingSenderId: '609604667702',
    projectId: 'selfcare-1476e',
    authDomain: 'selfcare-1476e.firebaseapp.com',
    storageBucket: 'selfcare-1476e.firebasestorage.app',
  );

}